### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by barneydobson** [ImperialCollegeLondon/SWMManywhere#10]
Intended use would be to have an initial setup config and one that intends to be executed many times. The main file (`swmmanywhere`) will have to create a file structure that works with this. I would envisage (reflected below) that there will be two folders - one for the preprocessing executaion (first config file), and one for the model creation (second config). Probably there will also be a national_downloads folder still

Run (once for a project) a slow to execute config (i.e., runnning downloaders and particularly slow graphfcns)
```
bbox:
    - minx
    - miny
    - maxx
    - maxy
project_name: my_project
run:
  base_directory_to_search: '' # empty because this is the first time to run for a project
  base_directory_to_save_to: 'base_project_dir'
  downloaders: 
  starting_graph: 
    - 'street.json'
    - 'river.json'
  list_of_functions:
      - graphfcn_A
      - graphfcn_B
      - graphfcn_C
```

Run (thousands of times in, e.g., for sensitivity analysis)
```
project_name: my_project
downloaders: False
run:
    -base_directory_to_search = 'folder in which output of pre_process is placed'
    -base_directory_to_save_to = 'another folder'
    -starting_graph: graphfcn_C.json
    -list_of_function:
        -graphfcnD
        -graphfcnE
        -graphfcnF
```
