### ISSUE TITLE
Run this workflow only when release is published. 

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/SWMManywhere#286]
https://github.com/ImperialCollegeLondon/SWMManywhere/blob/246b7f750fa2f40b5b06ceebdc0b8b28f2b63324/.github/workflows/publish.yml#L1

This should read:
```yaml
on:
  release:
    types: [published]
```
Otherwise the workflow is run multiple times.
